### ISSUE TITLE
optimization after fine-tuning causes exception

### ISSUE THREAD

**Issue by tderond** [biorack/omaat#10]
I commonly use the automatic spot optimization, fine-tune a few spots manually, and then run the automatic spot optimization again, but that seems to generate exceptions nowadays.
```TypeError                                 Traceback (most recent call last)
C:\Users\trist_000\PycharmProjects\omaat-march2017\omaat_lib.py in do_calculate(widget)
    499             imWidth=self.imStack.shape[1]
    500             imHeight=self.imStack.shape[0]
--> 501             numberOfSpots=len(self.xCenters)
    502             for box in ionWeightBoxes:
    503                 ionweights.append(box.value)

TypeError: object of type 'NoneType' has no len()
```

I suspect it has to do with
```        #xCenters and yCenters are required here and elsewhere
        self.get_xy_centers()
        xRough=self.xCenters
        yRough=self.yCenters
        # now that x and y centers have been initalized, reset x and y centers
        self.xCenters=None
        self.yCenters=None
```
in _fineTunePosition_. Could someone explain to me what the purpose of _get_xy_centers()_ is? I'm guessing I need to add that to the optimization function, but I want to understand why we're using that before I do.

**Comment by benbowen** [comment]
Can you describe your order of operations in more detail?  I can't reproduce the bug.  The way I understand it, these are the steps you are describing.

I did automatic positioning on round 1:
![image](https://cloud.githubusercontent.com/assets/810953/23864649/61099c9c-07d0-11e7-8396-fb0d6c39bc08.png)

and then move a spot out of position:
![image](https://cloud.githubusercontent.com/assets/810953/23864683/82290fde-07d0-11e7-88ea-1b5b67302714.png)

and then do automatic positioning:
![image](https://cloud.githubusercontent.com/assets/810953/23864754/b6019560-07d0-11e7-8bda-0e8893f1bab9.png)

Do you reinitialize "optimizeSpots_with_dialogs" each time you run it?

**Comment by tderond** [comment]
No I did not reinitialize "optimizeSpots_with_dialogs" every time, just clicked the button. That may be it.
I also often like to mix-and match graphical finetuning with programmatic optimization through "optimizeSpots" (which exposes more parameters), although this last time I used the button (multiple times)

**Comment by benbowen** [comment]
I just tried it without reinitializing and it worked.  I always use the interactive... I'm a sucker for buttons. Can you send me the parameters and how you call "optimizeSpots"?

**Comment by tderond** [comment]
I think I know what happened.
I almost always use the "calculate scores for current spots" button to help me set the minimum score, whenever i run an optimization. The error was actually happening at that point (as I _should_ have noticed from the `in do_calculate(widget)` in the exception, my bad, sorry about that). So clicking _that_ after running the finetune (but if you don't re-load the dialog) makes it happen. 
I'm pretty sure to fix this I just need to move the "self.get_xy_centers()" line from the _optimizeSpots_with_dialogs_ function to the _do_optimize_ inner function (there's already a `self.get_xy_centers()` in _optimizeSpots_ so _do_optimize_ doesn't need one.
