### ISSUE TITLE
rounding error for decimals

### ISSUE THREAD

**Issue by benbowen** [biorack/omaat#2]
According to @raad0102 there are rounding errors when processing data that have been normalized such that most intensities are decimals.  Lets check our division and decide on a test case.

**Comment by tderond** [comment]
Oh yes that's important to address!
@raad0102 do you have an example that breaks?

Now is actually a perfect time to address this because python 2 and 3
handle division differently

Tristan ⋈

**Comment by raad0102** [comment]
We have a collaborator which has the rounding errors. They agreed to share a file. I added both @benbowen and @tderond as viewers of the OpenMSI file. File name is NZGH_4

**Comment by tderond** [comment]
@raad0102 thanks! could you 1. give me a pickled ArrayedImage that causes this problem? 2. tell me which values you're expecting and which ones you're seeing in stead?

**Comment by raad0102** [comment]
1. Will send you the pickle file via email. 
2. I expect values greater than 0 (ranging from 0.01-250)

**Comment by tderond** [comment]
Interestingly, the results in the Pandas dataframe output are fine, but indeed there are rounding errors in the csv output. So the error is probably somewhere in the csv writing function but I haven't found it yet

**Comment by tderond** [comment]
Indeed it was the file writing that messed it up. An old line reading "fileHandler.write('%d,%d,%d,%d,%d,' % (np.sum(values),np.max(values),np.mean(values),np.median(values),len(values)))"

%d in this notation means a placeholder with integer formatting. replaced %d with %f (float) in the necessary locations

string formatting using % is deprecated in python 3 btw
